name: "classifier_small"

dataset:
  name: "zoo_small.csv"
  splits: [0.5, 0.25, 0.25]
  batch_size: 128
  seed: 42

hyperparameters:
  epochs: 20
  learning_rate: 0.005
  optimizer: "adam"
  criterion: "bce"
  seed: 42

model:
  input_dim: 33
  hidden_dims: [50, 20]
  output_dim: 8
  use_batch_norm: True
  dropout: 0.2
  output_activation: "softmax"
