name: "classifier_latent"

dataset:
  name: "zoo_small_extra.csv"
  splits: [0.7, 0.2, 0.1]
  batch_size: 128
  seed: 42

hyperparameters:
  epochs: 50
  learning_rate: 0.0001
  optimizer: "adam"
  criterion: "bce"
  seed: 42

model:
  input_dim: 10
  hidden_dims: [200, 100]
  output_dim: 8
  use_batch_norm: True
  dropout: 0.4
  output_activation: "softmax"
